apiVersion: v1
kind: Service
metadata:
  name: np-service
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 80 #Container Port
    nodePort: 32001 #Port range 30000-32767